{
   "status":"OK",
   "copyright":"Copyright (c) 2017 Pro Publica Inc. All Rights Reserved.",
   "results":[
      {
         "congress": "115",
         "chamber": "House",
         "num_results": "20",
         "offset": "0",
         "bills": [
              {
                 "bill_id": "hres271-115",
                 "bill_type": "hres",
                 "number": "H.RES.271",
                 "bill_uri": "https://api.propublica.org/congress/v1/115/bills/hres271.json",
                 "title": "Expressing the sense of the House of Representatives that the United States Trade Representative should commence negotiations to enter into a bilateral trade agreement with Taiwan.",
                 "sponsor_id": "Y000065",
                 "sponsor_uri": "https://api.propublica.org/congress/v1/members/Y000065.json",
                 "gpo_pdf_uri": "",
                 "congressdotgov_url": "https://www.congress.gov/bill/115th-congress/house-resolution/271",
                 "govtrack_url": "https://www.govtrack.us/congress/bills/115/hres271",
                 "introduced_date": "April  6, 2017",
                 "active": "false",
                 "house_passage": "",
                 "senate_passage": "",
                 "enacted": "",
                 "vetoed": "",
                 "cosponsors": "4",
                 "committees": "House Ways and Means Committee",
                 "primary_subject": "",
                 "summary": "",
                 "summary_short": "",
                 "latest_major_action_date": "April  6, 2017",
                 "latest_major_action": "Referred to the House Committee on Ways and Means."
              },
                           {
                 "bill_id": "hres270-115",
                 "bill_type": "hres",
                 "number": "H.RES.270",
                 "bill_uri": "https://api.propublica.org/congress/v1/115/bills/hres270.json",
                 "title": "Supporting the goals and ideals of National Public Health Week.",
                 "sponsor_id": "R000486",
                 "sponsor_uri": "https://api.propublica.org/congress/v1/members/R000486.json",
                 "gpo_pdf_uri": "",
                 "congressdotgov_url": "https://www.congress.gov/bill/115th-congress/house-resolution/270",
                 "govtrack_url": "https://www.govtrack.us/congress/bills/115/hres270",
                 "introduced_date": "April  6, 2017",
                 "active": "false",
                 "house_passage": "",
                 "senate_passage": "",
                 "enacted": "",
                 "vetoed": "",
                 "cosponsors": "19",
                 "committees": "House Energy and Commerce Committee",
                 "primary_subject": "",
                 "summary": "",
                 "summary_short": "",
                 "latest_major_action_date": "April  6, 2017",
                 "latest_major_action": "Referred to the House Committee on Energy and Commerce."
              },
                           {
                 "bill_id": "hres269-115",
                 "bill_type": "hres",
                 "number": "H.RES.269",
                 "bill_uri": "https://api.propublica.org/congress/v1/115/bills/hres269.json",
                 "title": "Recognizing and supporting the goals and ideals of National Sexual Assault Awareness and Prevention Month.",
                 "sponsor_id": "R000585",
                 "sponsor_uri": "https://api.propublica.org/congress/v1/members/R000585.json",
                 "gpo_pdf_uri": "",
                 "congressdotgov_url": "https://www.congress.gov/bill/115th-congress/house-resolution/269",
                 "govtrack_url": "https://www.govtrack.us/congress/bills/115/hres269",
                 "introduced_date": "April  6, 2017",
                 "active": "false",
                 "house_passage": "",
                 "senate_passage": "",
                 "enacted": "",
                 "vetoed": "",
                 "cosponsors": "53",
                 "committees": "House Judiciary Committee",
                 "primary_subject": "Crime and Law Enforcement",
                 "summary": "",
                 "summary_short": "",
                 "latest_major_action_date": "April  6, 2017",
                 "latest_major_action": "Referred to the House Committee on the Judiciary."
              },
                           {
                 "bill_id": "hres268-115",
                 "bill_type": "hres",
                 "number": "H.RES.268",
                 "bill_uri": "https://api.propublica.org/congress/v1/115/bills/hres268.json",
                 "title": "Expressing the sense of the House of Representatives regarding the trafficking of illicit fentanyl into the United States from Mexico and China.",
                 "sponsor_id": "M001180",
                 "sponsor_uri": "https://api.propublica.org/congress/v1/members/M001180.json",
                 "gpo_pdf_uri": "",
                 "congressdotgov_url": "https://www.congress.gov/bill/115th-congress/house-resolution/268",
                 "govtrack_url": "https://www.govtrack.us/congress/bills/115/hres268",
                 "introduced_date": "April  6, 2017",
                 "active": "false",
                 "house_passage": "",
                 "senate_passage": "",
                 "enacted": "",
                 "vetoed": "",
                 "cosponsors": "3",
                 "committees": "House Energy and Commerce Committee",
                 "primary_subject": "",
                 "summary": "",
                 "summary_short": "",
                 "latest_major_action_date": "April  6, 2017",
                 "latest_major_action": "Referred to House Energy and Commerce"
              },
                           {
                 "bill_id": "hres267-115",
                 "bill_type": "hres",
                 "number": "H.RES.267",
                 "bill_uri": "https://api.propublica.org/congress/v1/115/bills/hres267.json",
                 "title": "Recognizing the 100th anniversary of the 1st Infantry Division.",
                 "sponsor_id": "M001198",
                 "sponsor_uri": "https://api.propublica.org/congress/v1/members/M001198.json",
                 "gpo_pdf_uri": "",
                 "congressdotgov_url": "https://www.congress.gov/bill/115th-congress/house-resolution/267",
                 "govtrack_url": "https://www.govtrack.us/congress/bills/115/hres267",
                 "introduced_date": "April  6, 2017",
                 "active": "false",
                 "house_passage": "",
                 "senate_passage": "",
                 "enacted": "",
                 "vetoed": "",
                 "cosponsors": "2",
                 "committees": "House Armed Services Committee",
                 "primary_subject": "",
                 "summary": "",
                 "summary_short": "",
                 "latest_major_action_date": "April  6, 2017",
                 "latest_major_action": "Referred to the House Committee on Armed Services."
              },
                           {
                 "bill_id": "hres266-115",
                 "bill_type": "hres",
                 "number": "H.RES.266",
                 "bill_uri": "https://api.propublica.org/congress/v1/115/bills/hres266.json",
                 "title": "Designating the week of April 15, 2017, through April 23, 2017, as 'National Park Week'.",
                 "sponsor_id": "L000584",
                 "sponsor_uri": "https://api.propublica.org/congress/v1/members/L000584.json",
                 "gpo_pdf_uri": "",
                 "congressdotgov_url": "https://www.congress.gov/bill/115th-congress/house-resolution/266",
                 "govtrack_url": "https://www.govtrack.us/congress/bills/115/hres266",
                 "introduced_date": "April  6, 2017",
                 "active": "false",
                 "house_passage": "",
                 "senate_passage": "",
                 "enacted": "",
                 "vetoed": "",
                 "cosponsors": "4",
                 "committees": "House Natural Resources Committee",
                 "primary_subject": "",
                 "summary": "",
                 "summary_short": "",
                 "latest_major_action_date": "April  6, 2017",
                 "latest_major_action": "Referred to the House Committee on Natural Resources."
              },
                           {
                 "bill_id": "hres265-115",
                 "bill_type": "hres",
                 "number": "H.RES.265",
                 "bill_uri": "https://api.propublica.org/congress/v1/115/bills/hres265.json",
                 "title": "Expressing support for the designation of the week of April 24, 2017, through April 28, 2017, as National Specialized Instructional Support Personnel Awareness Week.",
                 "sponsor_id": "L000565",
                 "sponsor_uri": "https://api.propublica.org/congress/v1/members/L000565.json",
                 "gpo_pdf_uri": "",
                 "congressdotgov_url": "https://www.congress.gov/bill/115th-congress/house-resolution/265",
                 "govtrack_url": "https://www.govtrack.us/congress/bills/115/hres265",
                 "introduced_date": "April  6, 2017",
                 "active": "false",
                 "house_passage": "",
                 "senate_passage": "",
                 "enacted": "",
                 "vetoed": "",
                 "cosponsors": "1",
                 "committees": "House Energy and Commerce Committee",
                 "primary_subject": "",
                 "summary": "",
                 "summary_short": "",
                 "latest_major_action_date": "April  6, 2017",
                 "latest_major_action": "Referred to House Energy and Commerce"
              },
                           {
                 "bill_id": "hres264-115",
                 "bill_type": "hres",
                 "number": "H.RES.264",
                 "bill_uri": "https://api.propublica.org/congress/v1/115/bills/hres264.json",
                 "title": "Supporting the goals and ideals of Mathematics and Statistics Awareness Month.",
                 "sponsor_id": "L000563",
                 "sponsor_uri": "https://api.propublica.org/congress/v1/members/L000563.json",
                 "gpo_pdf_uri": "",
                 "congressdotgov_url": "https://www.congress.gov/bill/115th-congress/house-resolution/264",
                 "govtrack_url": "https://www.govtrack.us/congress/bills/115/hres264",
                 "introduced_date": "April  6, 2017",
                 "active": "false",
                 "house_passage": "",
                 "senate_passage": "",
                 "enacted": "",
                 "vetoed": "",
                 "cosponsors": "10",
                 "committees": "House Education and the Workforce Committee",
                 "primary_subject": "",
                 "summary": "",
                 "summary_short": "",
                 "latest_major_action_date": "April  6, 2017",
                 "latest_major_action": "Referred to the House Committee on Education and the Workforce."
              },
                           {
                 "bill_id": "hres263-115",
                 "bill_type": "hres",
                 "number": "H.RES.263",
                 "bill_uri": "https://api.propublica.org/congress/v1/115/bills/hres263.json",
                 "title": "Expressing support for the designation of May 4, 2017, as a 'National Day of Reason' and recognizing the importance of reason in the betterment of humanity.",
                 "sponsor_id": "L000582",
                 "sponsor_uri": "https://api.propublica.org/congress/v1/members/L000582.json",
                 "gpo_pdf_uri": "",
                 "congressdotgov_url": "https://www.congress.gov/bill/115th-congress/house-resolution/263",
                 "govtrack_url": "https://www.govtrack.us/congress/bills/115/hres263",
                 "introduced_date": "April  6, 2017",
                 "active": "false",
                 "house_passage": "",
                 "senate_passage": "",
                 "enacted": "",
                 "vetoed": "",
                 "cosponsors": "3",
                 "committees": "House Oversight and Government Reform Committee",
                 "primary_subject": "",
                 "summary": "",
                 "summary_short": "",
                 "latest_major_action_date": "April  6, 2017",
                 "latest_major_action": "Referred to the House Committee on Oversight and Government Reform."
              },
                           {
                 "bill_id": "hres262-115",
                 "bill_type": "hres",
                 "number": "H.RES.262",
                 "bill_uri": "https://api.propublica.org/congress/v1/115/bills/hres262.json",
                 "title": "Supporting the goals and ideals of National Youth HIV & AIDS Awareness Day.",
                 "sponsor_id": "L000551",
                 "sponsor_uri": "https://api.propublica.org/congress/v1/members/L000551.json",
                 "gpo_pdf_uri": "",
                 "congressdotgov_url": "https://www.congress.gov/bill/115th-congress/house-resolution/262",
                 "govtrack_url": "https://www.govtrack.us/congress/bills/115/hres262",
                 "introduced_date": "April  6, 2017",
                 "active": "false",
                 "house_passage": "",
                 "senate_passage": "",
                 "enacted": "",
                 "vetoed": "",
                 "cosponsors": "0",
                 "committees": "House Energy and Commerce Committee",
                 "primary_subject": "",
                 "summary": "",
                 "summary_short": "",
                 "latest_major_action_date": "April  6, 2017",
                 "latest_major_action": "Referred to the House Committee on Energy and Commerce."
              },
                           {
                 "bill_id": "hres261-115",
                 "bill_type": "hres",
                 "number": "H.RES.261",
                 "bill_uri": "https://api.propublica.org/congress/v1/115/bills/hres261.json",
                 "title": "Honoring and remembering on National Former POW Recognition Day and the 75th Anniversary of the Fall of Bataan on the Philippine Islands, the brave men and women who as prisoners of war gave their liberty to ensure ours, thus embodying the enduring spirit of American freedom and determination.",
                 "sponsor_id": "H001048",
                 "sponsor_uri": "https://api.propublica.org/congress/v1/members/H001048.json",
                 "gpo_pdf_uri": "",
                 "congressdotgov_url": "https://www.congress.gov/bill/115th-congress/house-resolution/261",
                 "govtrack_url": "https://www.govtrack.us/congress/bills/115/hres261",
                 "introduced_date": "April  6, 2017",
                 "active": "false",
                 "house_passage": "",
                 "senate_passage": "",
                 "enacted": "",
                 "vetoed": "",
                 "cosponsors": "5",
                 "committees": "House Foreign Affairs Committee",
                 "primary_subject": "",
                 "summary": "",
                 "summary_short": "",
                 "latest_major_action_date": "April  6, 2017",
                 "latest_major_action": "Referred to the House Committee on Foreign Affairs."
              },
                           {
                 "bill_id": "hres260-115",
                 "bill_type": "hres",
                 "number": "H.RES.260",
                 "bill_uri": "https://api.propublica.org/congress/v1/115/bills/hres260.json",
                 "title": "Expressing the sense of the House of Representatives in support of the International Atomic Energy Agency's (IAEA) nuclear security role.",
                 "sponsor_id": "F000454",
                 "sponsor_uri": "https://api.propublica.org/congress/v1/members/F000454.json",
                 "gpo_pdf_uri": "",
                 "congressdotgov_url": "https://www.congress.gov/bill/115th-congress/house-resolution/260",
                 "govtrack_url": "https://www.govtrack.us/congress/bills/115/hres260",
                 "introduced_date": "April  6, 2017",
                 "active": "false",
                 "house_passage": "",
                 "senate_passage": "",
                 "enacted": "",
                 "vetoed": "",
                 "cosponsors": "2",
                 "committees": "House Foreign Affairs Committee",
                 "primary_subject": "",
                 "summary": "",
                 "summary_short": "",
                 "latest_major_action_date": "April  6, 2017",
                 "latest_major_action": "Referred to the House Committee on Foreign Affairs."
              },
                           {
                 "bill_id": "hres259-115",
                 "bill_type": "hres",
                 "number": "H.RES.259",
                 "bill_uri": "https://api.propublica.org/congress/v1/115/bills/hres259.json",
                 "title": "Expressing concern and condemnation over the political, economic, social, and humanitarian crisis in Venezuela.",
                 "sponsor_id": "D000621",
                 "sponsor_uri": "https://api.propublica.org/congress/v1/members/D000621.json",
                 "gpo_pdf_uri": "",
                 "congressdotgov_url": "https://www.congress.gov/bill/115th-congress/house-resolution/259",
                 "govtrack_url": "https://www.govtrack.us/congress/bills/115/hres259",
                 "introduced_date": "April  6, 2017",
                 "active": "false",
                 "house_passage": "",
                 "senate_passage": "",
                 "enacted": "",
                 "vetoed": "",
                 "cosponsors": "8",
                 "committees": "House Foreign Affairs Committee",
                 "primary_subject": "",
                 "summary": "",
                 "summary_short": "",
                 "latest_major_action_date": "April  6, 2017",
                 "latest_major_action": "Referred to the House Committee on Foreign Affairs."
              },
                           {
                 "bill_id": "hres258-115",
                 "bill_type": "hres",
                 "number": "H.RES.258",
                 "bill_uri": "https://api.propublica.org/congress/v1/115/bills/hres258.json",
                 "title": "Urging the Secretary of Veterans Affairs to prioritize the hiring of mental health professionals.",
                 "sponsor_id": "C001111",
                 "sponsor_uri": "https://api.propublica.org/congress/v1/members/C001111.json",
                 "gpo_pdf_uri": "",
                 "congressdotgov_url": "https://www.congress.gov/bill/115th-congress/house-resolution/258",
                 "govtrack_url": "https://www.govtrack.us/congress/bills/115/hres258",
                 "introduced_date": "April  6, 2017",
                 "active": "false",
                 "house_passage": "",
                 "senate_passage": "",
                 "enacted": "",
                 "vetoed": "",
                 "cosponsors": "0",
                 "committees": "House Veterans&#39; Affairs Committee",
                 "primary_subject": "",
                 "summary": "",
                 "summary_short": "",
                 "latest_major_action_date": "April  6, 2017",
                 "latest_major_action": "Referred to the House Committee on Veterans&#39; Affairs."
              },
                           {
                 "bill_id": "hres257-115",
                 "bill_type": "hres",
                 "number": "H.RES.257",
                 "bill_uri": "https://api.propublica.org/congress/v1/115/bills/hres257.json",
                 "title": "Condemning hate crime and any other form of racism, religious or ethnic bias, discrimination, incitement to violence, or animus targeting a minority in the United States.",
                 "sponsor_id": "C001105",
                 "sponsor_uri": "https://api.propublica.org/congress/v1/members/C001105.json",
                 "gpo_pdf_uri": "",
                 "congressdotgov_url": "https://www.congress.gov/bill/115th-congress/house-resolution/257",
                 "govtrack_url": "https://www.govtrack.us/congress/bills/115/hres257",
                 "introduced_date": "April  6, 2017",
                 "active": "false",
                 "house_passage": "",
                 "senate_passage": "",
                 "enacted": "",
                 "vetoed": "",
                 "cosponsors": "3",
                 "committees": "House Judiciary Committee",
                 "primary_subject": "",
                 "summary": "",
                 "summary_short": "",
                 "latest_major_action_date": "April  6, 2017",
                 "latest_major_action": "Referred to the House Committee on the Judiciary."
              },
                           {
                 "bill_id": "hres256-115",
                 "bill_type": "hres",
                 "number": "H.RES.256",
                 "bill_uri": "https://api.propublica.org/congress/v1/115/bills/hres256.json",
                 "title": "Expressing support for the countries of Eastern Europe and the North Atlantic Treaty Organization.",
                 "sponsor_id": "C001068",
                 "sponsor_uri": "https://api.propublica.org/congress/v1/members/C001068.json",
                 "gpo_pdf_uri": "",
                 "congressdotgov_url": "https://www.congress.gov/bill/115th-congress/house-resolution/256",
                 "govtrack_url": "https://www.govtrack.us/congress/bills/115/hres256",
                 "introduced_date": "April  6, 2017",
                 "active": "false",
                 "house_passage": "",
                 "senate_passage": "",
                 "enacted": "",
                 "vetoed": "",
                 "cosponsors": "34",
                 "committees": "House Foreign Affairs Committee",
                 "primary_subject": "",
                 "summary": "",
                 "summary_short": "",
                 "latest_major_action_date": "April  6, 2017",
                 "latest_major_action": "Referred to the House Committee on Foreign Affairs."
              },
                           {
                 "bill_id": "hres255-115",
                 "bill_type": "hres",
                 "number": "H.RES.255",
                 "bill_uri": "https://api.propublica.org/congress/v1/115/bills/hres255.json",
                 "title": "Commemorating the 30th anniversary of United States Special Operations Command.",
                 "sponsor_id": "C001066",
                 "sponsor_uri": "https://api.propublica.org/congress/v1/members/C001066.json",
                 "gpo_pdf_uri": "",
                 "congressdotgov_url": "https://www.congress.gov/bill/115th-congress/house-resolution/255",
                 "govtrack_url": "https://www.govtrack.us/congress/bills/115/hres255",
                 "introduced_date": "April  6, 2017",
                 "active": "false",
                 "house_passage": "",
                 "senate_passage": "",
                 "enacted": "",
                 "vetoed": "",
                 "cosponsors": "3",
                 "committees": "House Armed Services Committee",
                 "primary_subject": "",
                 "summary": "",
                 "summary_short": "",
                 "latest_major_action_date": "April  6, 2017",
                 "latest_major_action": "Referred to the House Committee on Armed Services."
              },
                           {
                 "bill_id": "hres254-115",
                 "bill_type": "hres",
                 "number": "H.RES.254",
                 "bill_uri": "https://api.propublica.org/congress/v1/115/bills/hres254.json",
                 "title": "Providing for further consideration of the bill (H.R. 1628) to provide for reconciliation pursuant to title II of the concurrent resolution on the budget for fiscal year 2017.",
                 "sponsor_id": "S000250",
                 "sponsor_uri": "https://api.propublica.org/congress/v1/members/S000250.json",
                 "gpo_pdf_uri": "",
                 "congressdotgov_url": "https://www.congress.gov/bill/115th-congress/house-resolution/254",
                 "govtrack_url": "https://www.govtrack.us/congress/bills/115/hres254",
                 "introduced_date": "April  6, 2017",
                 "active": "true",
                 "house_passage": "",
                 "senate_passage": "",
                 "enacted": "",
                 "vetoed": "",
                 "cosponsors": "0",
                 "committees": "House Rules Committee",
                 "primary_subject": "",
                 "summary": "",
                 "summary_short": "",
                 "latest_major_action_date": "April  6, 2017",
                 "latest_major_action": "Placed on the House Calendar, Calendar No. 39."
              },
                           {
                 "bill_id": "hres253-115",
                 "bill_type": "hres",
                 "number": "H.RES.253",
                 "bill_uri": "https://api.propublica.org/congress/v1/115/bills/hres253.json",
                 "title": "Expressing gratitude and appreciation for the entry of the United States into World War I.",
                 "sponsor_id": "W000795",
                 "sponsor_uri": "https://api.propublica.org/congress/v1/members/W000795.json",
                 "gpo_pdf_uri": "",
                 "congressdotgov_url": "https://www.congress.gov/bill/115th-congress/house-resolution/253",
                 "govtrack_url": "https://www.govtrack.us/congress/bills/115/hres253",
                 "introduced_date": "April  6, 2017",
                 "active": "false",
                 "house_passage": "",
                 "senate_passage": "",
                 "enacted": "",
                 "vetoed": "",
                 "cosponsors": "3",
                 "committees": "House Armed Services Committee",
                 "primary_subject": "",
                 "summary": "",
                 "summary_short": "",
                 "latest_major_action_date": "April  6, 2017",
                 "latest_major_action": "Referred to House Armed Services"
              },
                           {
                 "bill_id": "hres252-115",
                 "bill_type": "hres",
                 "number": "H.RES.252",
                 "bill_uri": "https://api.propublica.org/congress/v1/115/bills/hres252.json",
                 "title": "Expressing the sense of the House of Representatives on the challenges posed to long-term stability in Lebanon by the conflict in Syria and supporting the establishment of safe zones in Syria.",
                 "sponsor_id": "L000585",
                 "sponsor_uri": "https://api.propublica.org/congress/v1/members/L000585.json",
                 "gpo_pdf_uri": "",
                 "congressdotgov_url": "https://www.congress.gov/bill/115th-congress/house-resolution/252",
                 "govtrack_url": "https://www.govtrack.us/congress/bills/115/hres252",
                 "introduced_date": "April  6, 2017",
                 "active": "false",
                 "house_passage": "",
                 "senate_passage": "",
                 "enacted": "",
                 "vetoed": "",
                 "cosponsors": "2",
                 "committees": "House Foreign Affairs Committee",
                 "primary_subject": "",
                 "summary": "",
                 "summary_short": "",
                 "latest_major_action_date": "April  6, 2017",
                 "latest_major_action": "Referred to the House Committee on Foreign Affairs."
              }
             ]
      }
   ]
}
